### ISSUE TITLE
bugs and weird things

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#1534] opened 2018-10-20 10:45 UTC
- if you have f1 opened and use arrow keys to get previous written message typed to f1 it will also use the arrow keys in the normal menues if possible

//fixed i guess - flag isnt fixed on other players

- skins are wrong rendered

- happy eyes and pain eyes look weird

- countryflags in scoreboard are too bright

- the set server mode (all, favourites, teeworlds) in the browser isnt saved -> reset after restart

- chat and hud isnt displayed when menu is opened

- motd is just displayed for half a sec

- menus are not that clear anymore (chaos for me)

- cant change info ingame (even if its wanted, its just crap for everybody i talked to)

- old maps are broken (design -> bcs tw now has broderadd and the stuff implemented in the client)

there are many things that the community doesnt like. imo it was a dumb decision to release 0.7 now, as its state looks very rushed and unfinished.
and btw: whats the problem with modding in tw? its an open source game, what do you expect?

- broadcast removed, for what reasons?

- showing id ingame in front of the name looks weird

- esc menu looks weird

- client id shown in kill message is also weird

- sometimes all buttons are hightlighted (as you would hover over every button at the same time)

- the markings of some skins arent shown in the team version of the skin (blue, red)

- default tilesets got changed so maps are fucked up

**Comment by Dune-jr** [comment] 2018-11-05 16:36
- [ ] if you have f1 opened and use arrow keys to get previous written message typed to f1 it will also use the arrow keys in the normal menus if possible

I can confirm, I will open an issue and probably get it fixed myself alongside #1589 

- [x] flag isnt fixed on other players

Fixed by 18e293ee6215bbeff34434118f84b7b564a1d349

- [ ] skins are wrong rendered

That is? The skin system was changed, but what is wrong?

- [ ] happy eyes and pain eyes look weird

Mind to expand on that?

- [x] countryflags in scoreboard are too bright

Probably related to #1576.

- [ ] the set server mode (all, favourites, teeworlds) in the browser isnt saved -> reset after restart

Will open an issue.

- [ ] chat and hud isnt displayed when menu is opened

Will open an issue.

- [x] motd is just displayed for half a sec

Fixed by #1545.

- [x] menus are not that clear anymore (chaos for me)

That's broad. #1551, #1576, #1597, #1538 address various menus issues.

- [x] cant change info ingame (even if its wanted, its just crap for everybody i talked to)

That is by design. What is the use of a name if you absolutely need to change it *during* a game?

- [ ] default tilesets got changed so maps are fucked up

Will open an issue.

- [ ] old maps are broken (design -> bcs tw now has broderadd and the stuff implemented in the client)

Isn't that the same as the issue above?

- [x] broadcast removed, for what reasons?

#1529

- [x] showing id ingame in front of the name looks weird

#1591

- [ ] esc menu looks weird

I agree. This should probably be an issue.

- [x] client id shown in kill message is also weird

#1591

- [ ] sometimes all buttons are highlighted (as you would hover over every button at the same time)

Will open an issue.

- [x] the markings of some skins arent shown in the team version of the skin (blue, red)

Fixed by #1606

**Comment by Dune-jr** [comment] 2018-11-06 08:58
@Zatline so it should be changed again?

**Comment by oy** [comment] 2018-11-06 16:55
> the set server mode (all, favourites, teeworlds) in the browser isnt saved -> reset after restart

This should work already 656ed30d6d34f431ae04671f2ae9edf2657234ea

**Comment by Zatline** [comment] 2018-11-07 05:10
@Dune-jr happy & pain eyes should not overlap but also not have big gap yea, fixed the png files.

![667b5af15a175860b2e20bb257e4dd5e](https://user-images.githubusercontent.com/344608/48111839-bd3f3800-e253-11e8-8c78-3cf174c2e99b.png)

**Comment by Dune-jr** [comment] 2018-11-13 18:52
@oy I would propose to close this, all the valid issues were listed elsewhere or fixed.

**Closed** 2018-11-13 19:18 UTC
