### ISSUE TITLE
Make ingame serverbrowser

### ISSUE THREAD

**Issue by chachacha3** [teeworlds/teeworlds#1552] opened 2018-10-24 10:51 UTC
Make ingame serverbrowser.

**Comment by jordy-ruiz** [comment] 2018-10-24 11:20
Duplicate of #651

**Comment by oy** [comment] 2018-10-24 18:08
Yeah, don't like an ingame server browser. But some friend indicator might be useful.

**Comment by themisak** [comment] 2018-11-10 14:39
Please Teeworlds Devs for once in a livetime listen to the community and its needs ...

**Comment by LordSk** [comment] 2019-05-05 08:54
So where are we going with this? I feel like the in-game server browser is an essential *social* feature.
* It allows you to plan where to go next with the people in the server you're already in.
* It allows you to see where your friends might be without leaving the people you're already with.

Now of course we can think of a better way of doing this, but for now it would seem reasonable to enable server browsing in game. The form of it is also important, should it be exactly like the main menu one? Should it be simpler?

**Comment by Sonix-** [comment] 2019-05-05 09:51
The form of the browser should be looking like the one in the main menu or something close to it, I'd go with adding the main menu one and then proceed with simplifying it.. f.e: 
- create premade lists/tabs with "recent" and "friends playing" lists/tabs.
- Selectable/premade gametype filter boxes to simplify and avoid typing in? (only vanilla ones, you could still type in mods)
![47601317-c692ef80-d98b-11e8-994e-d8ba1edba3ba](https://user-images.githubusercontent.com/2030615/57191978-c91e6500-6f2b-11e9-84e5-d23294c595fd.jpg)

**Comment by oy** [comment] 2019-08-18 17:40
fixed by #1636

**Closed by oy** 2019-08-18 17:40 UTC
Labels: design discussion, feature
