### ISSUE TITLE
emoticon window

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#1829] opened 2018-12-10 13:12 UTC
while the window is opened you cant move/shoot/hook. also the current movement gets copied (for example if youre walking and then opening emote window you will keep walking)

**Comment by Dune-jr** [comment] 2018-12-10 13:14
Duplicate of #1761. Already fixed in https://github.com/teeworlds/teeworlds/commit/c4fbceb02e118ae370e02152e776d8c94ec1abd4

**Closed** 2018-12-10 13:16 UTC
