### ISSUE TITLE
Scoreboard and statboard with many players

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2356] opened 2020-01-01 14:22 UTC
If there are more than 16 players on a server the two boards are just bad. You cant check everyones stats. I know some dont like the ddnet scoreboard and/or say its too small on lower resolutions, but tbh we should go for it, in 2020 nobody really plays on a low resolution.

**Comment by Dune-jr** [comment] 2020-01-01 14:28
Duplicate of https://github.com/teeworlds/teeworlds/issues/1828

**Closed** 2020-01-01 16:02 UTC
