### ISSUE TITLE
wavpack detection

### ISSUE THREAD

**Issue by oy** [teeworlds/teeworlds#35] opened 2010-09-02 23:52 UTC
We right now supply the tiny decoder for unpacking wavpack files. Some systems like gentoo etc want to use their system version (4.5.1). Do some auto detection for this and support the different versions of the API or perhaps update our tiny decoder to a newer version. Different API version handling would be the nicest of these two options.

**Comment by heinrich5991** [comment] 2019-02-03 11:50
Fixed by #1730.

(Reverse-duplicate of #1875.)

**Closed** 2019-02-03 12:32 UTC
Labels: build system, code-related, feature
