### ISSUE TITLE
SDL.h missed by multiple source files

### ISSUE THREAD

**Issue by Henningstone** [teeworlds/teeworlds#1308] opened 2015-01-19 23:34 UTC
When compiling the latest git version of the teeworlds source, on windows at least, I expired several errors referring to a missing `SDL.h`. I got the following errors, every one telling `could not open SDL.h: No such file or directory`:

>src/engine/client/backend_sdl.cpp(2)
>src/engine/client/client.cpp(52)
>src/engine/client/input.cpp(3)
>src/engine/client/sound.cpp(11)
>src/engine/client/text.cpp(13)

Just to let you know. Don't know if it has to be like this or it was realized already.

**Comment by MegaManSec** [comment] 2015-01-20 07:33
http://www.libsdl.org/download-1.2.php
you are missing the library

**Comment by heinrich5991** [comment] 2015-01-20 12:37
I think this is a duplicate of #1275.

**Comment by Henningstone** [comment] 2015-01-20 14:15
You're right, it is. Maybe I am going

**Closed** 2015-01-20 14:46 UTC
