### ISSUE TITLE
Changing skin only take effect when you change the server

### ISSUE THREAD

**Issue by Zwelf** [teeworlds/teeworlds#1350] opened 2015-05-29 15:34 UTC
It would be great, if the skin change, when you change it in the options, like teeworlds 0.6 does it.

**Comment by Henningstone** [comment] 2015-06-03 10:54
Having it like it is now makes skin-changing or tee-faking bots impossible, though.

**Comment by heinrich5991** [comment] 2015-06-03 18:21
You can still reconnect using a faked skin. Also, such a "bot protection" should not go against the UX.

**Comment by Henningstone** [comment] 2015-06-04 09:44
Do you know Chameleon? This bot changes your tee data (so your name and Clan and skin and everything) to the tee data of the tee you hit, whenever you hit a tee. It's what I meant in my previous post.
Usual players have no reason to change their skin all the time while playing, do they? :O

**Comment by heinrich5991** [comment] 2015-06-05 16:02
Not all the time, but not being able to change your skin while in-game is bad for new users who experiment or users who like to change their skin once in a while.

Maybe more aggressive timeouts should be put in place.

**Comment by oy** [comment] 2015-07-01 18:48
Won't fix. This was pretty much just abused anyway and the skin selector provides a preview.

**Closed by oy** 2015-07-01 18:48 UTC

**Comment by Zwelf** [comment] 2015-08-02 10:47
It is better to make this option configurable from the server.
Skin changing is like changing the name. Do user need to change their name? Yes they do the same way they want to change theire skin.
And changing skin shouldn't be disabled neither. There should be a better protection if it is enabled.

**Comment by Henningstone** [comment] 2015-08-03 00:16
Hmm, "make it configurable" seems to be always the best solution for programmers, does it? We can't make false decisions if we leave every decision to the user :)
Ok but seriously: in this case I think that it might be the best solution. Change-botting the name is even more annoying because it is being announced in chat (but possible yet anyway).
Server owners who feel disturbed by eventual skin changing botters can turn instant skin change off before they need to start crying :/
In fact, quite everything can be abused in some way, but usual players shouldn't be affected by the consequences of "fixing" that. Just my personal opinion.

**Comment by heinrich5991** [comment] 2015-08-09 10:17
@Henningstone The chat can also be spammed in other ways, chat messages, join/leave spamming, etc. :)

**Comment by Henningstone** [comment] 2015-08-14 20:10
@heinrich5991 Mhh I forgot that vanilla has no feature to automatically mute players who are spamming chat messages :0
I think I play to less vanilla and to much modded teeworlds. My mistake :D

**Comment by Zwelf** [comment] 2015-11-02 09:11
What about only change the skin, if the character repawn. In my opinion this is a good solution, because it is as well a skin change protection. and it would be a compromise that you can change your skin ingame. I hope this issue will be reopened and this bug will be fixed.

**Comment by nheir** [comment] 2015-11-02 10:03
I feel like this is a feature and not a bug, looking at code.
But, this also prevents using skin changes on server side (that one can see with zcatch)… 
The client should trust the server and shouldn't assume that ClientInfo == new client.
