### ISSUE TITLE
Rcon settings autocompletion starts outside of my window

### ISSUE THREAD

**Issue by Fudgyking** [teeworlds/teeworlds#2084] opened 2019-04-01 15:45 UTC
Sometimes when I type a setting in the f2 console, the suggested results start appearing outside of my window, I cant quite tell how far outside but its enough to not see the result when there is only 1 matching setting.
It happened to me quite a few times but I don't know the exact steps to reproduce.

![screenshot_2019-04-01_11-42-10](https://user-images.githubusercontent.com/5041807/55340761-507f4100-5473-11e9-845e-3dd5ec44a8fd.png)

(Yes I play in 4:3 resolution)

**Comment by oy** [comment] 2019-04-28 17:25
Tested it a bit, can't reproduce it :(

**Comment by Fudgyking** [comment] 2019-04-28 17:27
> Tested it a bit, can't reproduce it :(

Did you try in 4:3 resolution? 

It's quite random, I didn't find consistent steps to reproduce :/

**Comment by oy** [comment] 2019-04-28 17:32
Yeah, did in 4:3

Found a way to reproduce it:
- press one char so you have lots possible completions and then tab along till you get an offset on the left
- then disconnect and connect/login again

**Comment by oy** [comment] 2019-04-28 18:05
Fixed by 2dae9d475152947c82e6576affdbb5a517e69d4c

**Closed by oy** 2019-04-28 18:05 UTC
Labels: bug, ui
