### ISSUE TITLE
damage indicator angle value not used

### ISSUE THREAD

**Issue by fokkonaut** [teeworlds/teeworlds#2787] opened 2020-10-23 15:11 UTC
would be cool to allow server to send an angle again without the client just ignoring it

**Comment by Dune-jr** [comment] 2020-10-23 16:20
Duplicate of https://github.com/teeworlds/teeworlds/issues/2141?

**Comment by fokkonaut** [comment] 2020-10-23 16:30
yea true, but something has to happen I think. its so bad right now :D

**Comment by Learath2** [comment] 2020-10-23 20:49
Well they work perfectly as damage indicators. We were kinda abusing them and they don't support that anymore. It's not really "bad". It's just disappointing :P

**Comment by oy** [comment] 2020-11-01 10:36
Duplicate #2141

**Closed by oy** 2020-11-01 10:36 UTC
