### ISSUE TITLE
Aborting map download and rejoining causes a crash

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds#2126] opened 2019-05-01 20:26 UTC
I can reliably make it crash on some 0.7.2 modified servers with a 64-bit debug mode windows Teeworlds, but not with Linux or when using some debugging tools, so I cannot provide a trace.

> Reproducible both on macOS and windows, cant check on linux
I did a screen record if that helps. Sometimes it doesnt crash even if I cancel downloadig and reconnect, but it also can crash on first attempt. The annoying thing is, you cant rejoin until you remove the .map file
> Oh, you still can redownload after some time

**Comment by oy** [comment] 2019-05-01 20:42
Seems you get banned when aborting the map download.

**Comment by Dune-jr** [comment] 2019-05-01 20:58
I often do, yeah. Not always

**Comment by oy** [comment] 2019-05-01 21:28
Can't reproduce it with 64bit debug windows, built with vs though :(

**Comment by sepulzera** [comment] 2019-05-02 09:32
> Seems you get banned when aborting the map download.

Guess being banned for stressing the network?
That often happens to me for my local server when mapping. Accidentally pressing enter twice = join + disconnect. Joining then again via enter = banned for 1 minute.
Quite annoying tbh.

**Comment by Dune-jr** [comment] 2019-05-02 12:32
Yes it's https://github.com/teeworlds/teeworlds/issues/1631

**Comment by Robyt3** [comment] 2020-02-09 14:33
Here is a log right before a crash:
```
[2020-02-09 15:13:42][client]: disconnecting. reason='unknown'
[2020-02-09 15:13:42][client]: state change. last=0 current=0
[2020-02-09 15:13:42][client]: connecting to '<a 0.7.2 RACE server>'
[2020-02-09 15:13:42][client]: state change. last=0 current=1
[2020-02-09 15:13:42][connection]: got token, replying, token=1b906445 mytoken=313c5aa4
[2020-02-09 15:13:42][connection]: got connect+accept, sending accept. connection online
[2020-02-09 15:13:42][client]: connected, sending info
[2020-02-09 15:13:42][client]: state change. last=1 current=2
[2020-02-09 15:13:42][client]: loading map, map=waterrun wanted crc=2bd30852
[2020-02-09 15:13:42][client]: state change. last=2 current=2
[2020-02-09 15:13:42][client]: state change. last=2 current=2
[2020-02-09 15:13:42][datafile]: loading. filename='maps/waterrun.map'
[2020-02-09 15:13:42][datafile]: could not open 'maps/waterrun.map'
[2020-02-09 15:13:42][client]: state change. last=2 current=2
[2020-02-09 15:13:42][datafile]: loading. filename='downloadedmaps/waterrun_2bd30852.map'
[2020-02-09 15:13:42][datafile]: allocsize=9384
[2020-02-09 15:13:42][datafile]: readsize=9096
[2020-02-09 15:13:42][datafile]: swaplen=9116
[2020-02-09 15:13:42][datafile]: item_size=8388
[2020-02-09 15:13:42][datafile]: loading done. datafile='downloadedmaps/waterrun_2bd30852.map'
[2020-02-09 15:13:42][datafile]: loading data index=24 size=196 uncompressed=972
[2020-02-09 15:13:42][datafile]: loading data index=27 size=161 uncompressed=828
[2020-02-09 15:13:42][datafile]: loading data index=28 size=693 uncompressed=3380
```
This happens after launching the client (current master, windows 64 debug mingw) and connecting to the server. Previously I launched the client and connected to the server, starting the map download, stopping and then reconnecting, thereby getting banned for 1 minute for stressing. Connecting during this 1 minute gives me the usual banned error. Connecting after being unbanned crashes (even after closing client first), probably because the map is already partially downloaded but invalid. So..

- Invalid map causes crash; which it should never do. Sample corrupted and complete map: [maps.zip](https://github.com/teeworlds/teeworlds/files/4177007/maps.zip)
  - Loading the corrupted map in the editor works but obviously it's corrupted
  - Starting a server with the corrupted map crashes the server:
```
[2020-02-09 15:31:35][datafile]: loading. filename='maps/waterrun_2bd30852_corrupted.map'
[2020-02-09 15:31:35][datafile]: allocsize=9384
[2020-02-09 15:31:35][datafile]: readsize=9096
[2020-02-09 15:31:35][datafile]: swaplen=9116
[2020-02-09 15:31:35][datafile]: item_size=8388
[2020-02-09 15:31:35][datafile]: loading done. datafile='maps/waterrun_2bd30852_corrupted.map'
[2020-02-09 15:31:35][datafile]: loading data index=24 size=196 uncompressed=972
```
- Partially downloaded map is not properly deleted when download is cancelled by being banned (maybe other conditions as well)
  - Add the relevant checks everywhere they are missing
  - Or could also do this more effectively: Download map as .temp file and rename once it's done. Delete all .temp files at exit.

**Closed** 2020-04-14 18:02 UTC
Labels: bug
