### ISSUE TITLE
Error while compiling official Teeworlds (last source-release 0.7.3.1) with bam5

### ISSUE THREAD

**Issue by KlobbenRillen** [teeworlds/teeworlds#2263] opened 2019-10-09 14:02 UTC
I get followed error while compiling teeworlds with **bam5 client**:
`[1/2] [1] c++ src/engine/client/backend_sdl.cpp
src/engine/client/backend_sdl.cpp:18:21: error: function 'void glTexImage3D(GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid*)' definition is marked dllimport
 GLAPI void APIENTRY glTexImage3D(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
                     ^~~~~~~~~~~~
src/engine/client/backend_sdl.cpp: In function 'void glTexImage3D(GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid*)':
src/engine/client/backend_sdl.cpp:18:21: warning: 'void glTexImage3D(GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid*)' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
bam: 'c++ src/engine/client/backend_sdl.cpp' error 1
bam: error: a build step failed`

**Comment by Dune-jr** [comment] 2019-10-09 14:04
I tried to do support in IRC, it came up that @KlobbenRillen is:
- on win10, 64bit
- using the supplied teeworlds libs from https://github.com/teeworlds/teeworlds-libs
- had the issue in 0.6.4
- can build with cmake/VS2017

I don't know what the issue is, though

**Comment by oy** [comment] 2019-10-10 19:36
@KlobbenRillen seems you built with mingw? could you check which version you have `gcc --version`?
If you use vs/cl as compiler `bam config compiler=cl` the build works?

**Comment by KlobbenRillen** [comment] 2019-10-10 20:24
I got followed response from `gcc --version`
```
gcc (i686-posix-sjlj-rev2, Built by MinGW-W64 project) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
and when i change the compiler to cl i get thousands of erros (command `cl` is not found)

**Comment by KlobbenRillen** [comment] 2019-10-11 16:28
I still cant compile with compiler = cl followed (german) errors occurred:
```
[1/3] [1] c++ src/engine/client/input.cpp
[2/3] [2] c++ src/game/client/components/camera.cpp
src/game/client/components/camera.cpp(103) : error C2666: 'pow': 6 Überladungen haben ähnliche Konvertierungen
        D:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(583): kann 'long double pow(long double,int)' sein
        D:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(581): oder "long double pow(long double,long double)"
        D:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(535): oder "float pow(float,int)"
        D:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(533): oder "float pow(float,float)"
        D:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(497): oder "double pow(double,int)"
        D:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(122): oder "double pow(double,double)"
        bei Anpassung der Argumentliste '(float, double)'
bam: 'c++ src/game/client/components/camera.cpp' error 2
src/engine/client/input.cpp(122) : error C3861: "fminf": Bezeichner wurde nicht gefunden.
bam: 'c++ src/engine/client/input.cpp' error 2
bam: error: a build step failed
```

**Comment by oy** [comment] 2019-10-11 18:39
@KlobbenRillen these should be fixed on latest master

**Comment by KlobbenRillen** [comment] 2019-10-11 18:43
works now with compiler = cl but gcc is still an issue :/

**Comment by oy** [comment] 2019-10-11 19:14
Yeah, but that's not related to bam, should fail with cmake too when you'd use gcc for it.
Will look into that.

**Comment by oy** [comment] 2019-10-12 15:16
@KlobbenRillen 
Could you replace this line
https://github.com/teeworlds/teeworlds/blob/master/src/engine/client/backend_sdl.cpp#L18

with
`GLAPI void GLAPIENTRY glTexImage3D(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels)`
and check if it compiles with gcc?

**Comment by KlobbenRillen** [comment] 2019-10-12 15:19
Does not work. Followed error occured:
```
[1/2] [1] c++ src/engine/client/backend_sdl.cpp
src/engine/client/backend_sdl.cpp:18:23: error: function 'void glTexImage3D(GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid*)' definition is marked dllimport
 GLAPI void GLAPIENTRY glTexImage3D(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
                       ^~~~~~~~~~~~
src/engine/client/backend_sdl.cpp: In function 'void glTexImage3D(GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid*)':
src/engine/client/backend_sdl.cpp:18:23: warning: 'void glTexImage3D(GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, const GLvoid*)' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
bam: 'c++ src/engine/client/backend_sdl.cpp' error 1
bam: error: a build step failed
```

**Comment by oy** [comment] 2019-10-12 15:26
Alright.
And 
`WINGDIAPI void APIENTRY glTexImage3D(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels)`
doesn't work either right?

**Comment by KlobbenRillen** [comment] 2019-10-12 15:27
Nope still same error :c

**Comment by oy** [comment] 2019-10-12 15:30
`void glTexImage3D(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels)`
That compiles right? If so could you check if the client works properly?

**Comment by KlobbenRillen** [comment] 2019-10-12 15:30
As I said the Dune (in the IRC talk we had) I do can compile it when the line is:
```cpp
void glTexImage3D(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
```
and after I found out that the data folder is not copied with `bam client` I had these error images (@Dune-jr this explains that)

**Comment by KlobbenRillen** [comment] 2019-10-12 15:31
So yeah, client seems work normally with that. No bugs or anything. Fully useable.

**Comment by oy** [comment] 2019-10-12 15:33
Alright 👍

**Comment by oy** [comment] 2019-10-12 15:40
Should work now on master.

**Closed** 2019-10-12 15:40 UTC
