### ISSUE TITLE
Gun position off again

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds/teeworlds#2244] opened 2019-09-25 17:53 UTC
As far as I know the gun position was a bit off in the early days of 0.6 but it got fixed in some 0.6 minor realse. But it seems like this change was reverted or not ported to 0.7.
<img width="634" alt="Unbenannt" src="https://user-images.githubusercontent.com/20344300/65626605-00baa600-dfce-11e9-828a-e063f5fa6cf2.PNG">

**Comment by fokkonaut** [comment] 2019-09-26 12:42
Wasnt it just fixed in ddnet?

**Comment by ChillerDragon** [comment] 2019-09-27 14:29
@fokkonaut because changes are harsh and people complained ddnet added a config to support both again. Default being the new/fixed one.

https://github.com/ddnet/ddnet/commit/a79b6079fa5056eff1f8f14e29f8f8a030b5c60f

As you can see in the description: Tees hold gun a bit higher like in TW 0.6.1 and older

And also my screenshots are taken with vanilla clients and later 0.6 clients have the correctly aligned gun.

**Comment by Dune-jr** [comment] 2019-09-27 14:48
Possible duplicate of https://github.com/teeworlds/teeworlds/issues/1013

**Comment by oy** [comment] 2019-09-28 12:28
Yeah, the gun position is off again, cause the fix got reverted so it doesn't look odd when aiming up or down. See discussion here #1013
Closing here, the other one is open for more discussion.

**Closed by oy** 2019-09-28 12:28 UTC
